[package]
name = "sdl2-engine-helpers"
version = "0.0.1"
authors = ["Tony Aldridge <zaragopha@hotmail.com>"]

[features]
default = []
# opengl = ["gl"]

[dependencies]
sdl2 = "0.31"
# gl = { version = "0.10.0", optional = true }
gl = { version = "0.10.0" }
